// Curated list of popular US stocks and ETFs for local search
export const STOCKS = [
  // Mega-cap tech
  { symbol: 'AAPL', name: 'Apple Inc.', type: 'EQUITY' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', type: 'EQUITY' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', type: 'EQUITY' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)', type: 'EQUITY' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)', type: 'EQUITY' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', type: 'EQUITY' },
  { symbol: 'META', name: 'Meta Platforms Inc.', type: 'EQUITY' },
  { symbol: 'TSLA', name: 'Tesla Inc.', type: 'EQUITY' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', type: 'EQUITY' },
  { symbol: 'ORCL', name: 'Oracle Corporation', type: 'EQUITY' },
  // Financials
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc.', type: 'EQUITY' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', type: 'EQUITY' },
  { symbol: 'V', name: 'Visa Inc.', type: 'EQUITY' },
  { symbol: 'MA', name: 'Mastercard Inc.', type: 'EQUITY' },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc.', type: 'EQUITY' },
  { symbol: 'MS', name: 'Morgan Stanley', type: 'EQUITY' },
  { symbol: 'BLK', name: 'BlackRock Inc.', type: 'EQUITY' },
  { symbol: 'AXP', name: 'American Express Company', type: 'EQUITY' },
  { symbol: 'COF', name: 'Capital One Financial', type: 'EQUITY' },
  { symbol: 'USB', name: 'U.S. Bancorp', type: 'EQUITY' },
  { symbol: 'PNC', name: 'PNC Financial Services', type: 'EQUITY' },
  { symbol: 'TFC', name: 'Truist Financial Corporation', type: 'EQUITY' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', type: 'EQUITY' },
  { symbol: 'MCO', name: "Moody's Corporation", type: 'EQUITY' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', type: 'EQUITY' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies', type: 'EQUITY' },
  { symbol: 'AON', name: 'Aon plc', type: 'EQUITY' },
  // Healthcare
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.', type: 'EQUITY' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', type: 'EQUITY' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', type: 'EQUITY' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', type: 'EQUITY' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', type: 'EQUITY' },
  { symbol: 'PFE', name: 'Pfizer Inc.', type: 'EQUITY' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', type: 'EQUITY' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', type: 'EQUITY' },
  { symbol: 'ABT', name: 'Abbott Laboratories', type: 'EQUITY' },
  { symbol: 'DHR', name: 'Danaher Corporation', type: 'EQUITY' },
  { symbol: 'MDT', name: 'Medtronic plc', type: 'EQUITY' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', type: 'EQUITY' },
  { symbol: 'AMGN', name: 'Amgen Inc.', type: 'EQUITY' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', type: 'EQUITY' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', type: 'EQUITY' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', type: 'EQUITY' },
  { symbol: 'SYK', name: 'Stryker Corporation', type: 'EQUITY' },
  { symbol: 'BDX', name: 'Becton Dickinson and Company', type: 'EQUITY' },
  { symbol: 'ELV', name: 'Elevance Health Inc.', type: 'EQUITY' },
  { symbol: 'HUM', name: 'Humana Inc.', type: 'EQUITY' },
  { symbol: 'CI', name: 'The Cigna Group', type: 'EQUITY' },
  { symbol: 'CVS', name: 'CVS Health Corporation', type: 'EQUITY' },
  { symbol: 'EW', name: 'Edwards Lifesciences', type: 'EQUITY' },
  // Consumer
  { symbol: 'AMZN', name: 'Amazon.com Inc.', type: 'EQUITY' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', type: 'EQUITY' },
  { symbol: 'WMT', name: 'Walmart Inc.', type: 'EQUITY' },
  { symbol: 'HD', name: 'The Home Depot Inc.', type: 'EQUITY' },
  { symbol: 'MCD', name: "McDonald's Corporation", type: 'EQUITY' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', type: 'EQUITY' },
  { symbol: 'NKE', name: 'NIKE Inc.', type: 'EQUITY' },
  { symbol: 'PG', name: 'Procter & Gamble Company', type: 'EQUITY' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', type: 'EQUITY' },
  { symbol: 'KO', name: 'Coca-Cola Company', type: 'EQUITY' },
  { symbol: 'PM', name: 'Philip Morris International', type: 'EQUITY' },
  { symbol: 'MO', name: 'Altria Group Inc.', type: 'EQUITY' },
  { symbol: 'MDLZ', name: 'Mondelez International', type: 'EQUITY' },
  { symbol: 'TGT', name: 'Target Corporation', type: 'EQUITY' },
  { symbol: 'LOW', name: "Lowe's Companies Inc.", type: 'EQUITY' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', type: 'EQUITY' },
  { symbol: 'DIS', name: 'The Walt Disney Company', type: 'EQUITY' },
  { symbol: 'NFLX', name: 'Netflix Inc.', type: 'EQUITY' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', type: 'EQUITY' },
  // Semiconductors & Tech
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', type: 'EQUITY' },
  { symbol: 'INTC', name: 'Intel Corporation', type: 'EQUITY' },
  { symbol: 'QCOM', name: 'Qualcomm Incorporated', type: 'EQUITY' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.', type: 'EQUITY' },
  { symbol: 'MU', name: 'Micron Technology Inc.', type: 'EQUITY' },
  { symbol: 'ADI', name: 'Analog Devices Inc.', type: 'EQUITY' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.', type: 'EQUITY' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', type: 'EQUITY' },
  { symbol: 'LRCX', name: 'Lam Research Corporation', type: 'EQUITY' },
  { symbol: 'KLAC', name: 'KLA Corporation', type: 'EQUITY' },
  { symbol: 'ASML', name: 'ASML Holding N.V.', type: 'EQUITY' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor', type: 'EQUITY' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems', type: 'EQUITY' },
  // Software / Cloud
  { symbol: 'ADBE', name: 'Adobe Inc.', type: 'EQUITY' },
  { symbol: 'CRM', name: 'Salesforce Inc.', type: 'EQUITY' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', type: 'EQUITY' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', type: 'EQUITY' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', type: 'EQUITY' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.', type: 'EQUITY' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', type: 'EQUITY' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', type: 'EQUITY' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', type: 'EQUITY' },
  { symbol: 'IBM', name: 'International Business Machines', type: 'EQUITY' },
  { symbol: 'ACN', name: 'Accenture plc', type: 'EQUITY' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.', type: 'EQUITY' },
  { symbol: 'LYFT', name: 'Lyft Inc.', type: 'EQUITY' },
  { symbol: 'SPOT', name: 'Spotify Technology', type: 'EQUITY' },
  { symbol: 'SHOP', name: 'Shopify Inc.', type: 'EQUITY' },
  { symbol: 'SNOW', name: 'Snowflake Inc.', type: 'EQUITY' },
  { symbol: 'PLTR', name: 'Palantir Technologies', type: 'EQUITY' },
  { symbol: 'COIN', name: 'Coinbase Global Inc.', type: 'EQUITY' },
  { symbol: 'RBLX', name: 'Roblox Corporation', type: 'EQUITY' },
  { symbol: 'HOOD', name: 'Robinhood Markets Inc.', type: 'EQUITY' },
  // Energy
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', type: 'EQUITY' },
  { symbol: 'CVX', name: 'Chevron Corporation', type: 'EQUITY' },
  { symbol: 'COP', name: 'ConocoPhillips', type: 'EQUITY' },
  { symbol: 'SLB', name: 'SLB (Schlumberger)', type: 'EQUITY' },
  { symbol: 'EOG', name: 'EOG Resources Inc.', type: 'EQUITY' },
  { symbol: 'OXY', name: 'Occidental Petroleum', type: 'EQUITY' },
  // Industrials
  { symbol: 'CAT', name: 'Caterpillar Inc.', type: 'EQUITY' },
  { symbol: 'HON', name: 'Honeywell International', type: 'EQUITY' },
  { symbol: 'UPS', name: 'United Parcel Service', type: 'EQUITY' },
  { symbol: 'FDX', name: 'FedEx Corporation', type: 'EQUITY' },
  { symbol: 'BA', name: 'Boeing Company', type: 'EQUITY' },
  { symbol: 'RTX', name: 'RTX Corporation', type: 'EQUITY' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation', type: 'EQUITY' },
  { symbol: 'GE', name: 'GE Aerospace', type: 'EQUITY' },
  { symbol: 'DE', name: 'Deere & Company', type: 'EQUITY' },
  { symbol: 'EMR', name: 'Emerson Electric Co.', type: 'EQUITY' },
  { symbol: 'ETN', name: 'Eaton Corporation plc', type: 'EQUITY' },
  { symbol: 'NSC', name: 'Norfolk Southern Corporation', type: 'EQUITY' },
  { symbol: 'GWW', name: 'W.W. Grainger Inc.', type: 'EQUITY' },
  { symbol: 'WM', name: 'Waste Management Inc.', type: 'EQUITY' },
  // Utilities / Real Estate
  { symbol: 'NEE', name: 'NextEra Energy Inc.', type: 'EQUITY' },
  { symbol: 'AMT', name: 'American Tower Corporation', type: 'EQUITY' },
  { symbol: 'PLD', name: 'Prologis Inc.', type: 'EQUITY' },
  { symbol: 'VZ', name: 'Verizon Communications', type: 'EQUITY' },
  { symbol: 'T', name: 'AT&T Inc.', type: 'EQUITY' },
  // Materials
  { symbol: 'LIN', name: 'Linde plc', type: 'EQUITY' },
  { symbol: 'SHW', name: 'Sherwin-Williams Company', type: 'EQUITY' },
  { symbol: 'ECL', name: 'Ecolab Inc.', type: 'EQUITY' },
  { symbol: 'APH', name: 'Amphenol Corporation', type: 'EQUITY' },
  // Other popular
  { symbol: 'KEYS', name: 'Keysight Technologies', type: 'EQUITY' },
  { symbol: 'MSTR', name: 'MicroStrategy Inc.', type: 'EQUITY' },
  { symbol: 'RIVN', name: 'Rivian Automotive Inc.', type: 'EQUITY' },
  { symbol: 'LCID', name: 'Lucid Group Inc.', type: 'EQUITY' },
  { symbol: 'GME', name: 'GameStop Corp.', type: 'EQUITY' },
  { symbol: 'AMC', name: 'AMC Entertainment Holdings', type: 'EQUITY' },
  { symbol: 'SOFI', name: 'SoFi Technologies Inc.', type: 'EQUITY' },
  { symbol: 'DKNG', name: 'DraftKings Inc.', type: 'EQUITY' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', type: 'EQUITY' },
  // Popular ETFs
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', type: 'ETF' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust (Nasdaq 100)', type: 'ETF' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF', type: 'ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', type: 'ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', type: 'ETF' },
  { symbol: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF', type: 'ETF' },
  { symbol: 'GLD', name: 'SPDR Gold Shares', type: 'ETF' },
  { symbol: 'SLV', name: 'iShares Silver Trust', type: 'ETF' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', type: 'ETF' },
  { symbol: 'HYG', name: 'iShares iBoxx High Yield Corporate Bond ETF', type: 'ETF' },
  { symbol: 'EEM', name: 'iShares MSCI Emerging Markets ETF', type: 'ETF' },
  { symbol: 'VNQ', name: 'Vanguard Real Estate ETF', type: 'ETF' },
  { symbol: 'XLK', name: 'Technology Select Sector SPDR', type: 'ETF' },
  { symbol: 'XLF', name: 'Financial Select Sector SPDR', type: 'ETF' },
  { symbol: 'XLV', name: 'Health Care Select Sector SPDR', type: 'ETF' },
  { symbol: 'XLE', name: 'Energy Select Sector SPDR', type: 'ETF' },
  { symbol: 'XLY', name: 'Consumer Discretionary Select SPDR', type: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', type: 'ETF' },
  { symbol: 'SQQQ', name: 'ProShares UltraPro Short QQQ', type: 'ETF' },
  { symbol: 'TQQQ', name: 'ProShares UltraPro QQQ', type: 'ETF' },
]

export function searchStocks(query) {
  const q = query.trim().toLowerCase()
  if (!q) return []
  const bySymbol = STOCKS.filter((s) => s.symbol.toLowerCase().startsWith(q))
  const byName = STOCKS.filter(
    (s) => !s.symbol.toLowerCase().startsWith(q) && s.name.toLowerCase().includes(q)
  )
  return [...bySymbol, ...byName].slice(0, 8)
}
